SYNC_COLLECTIONS = [
    {
        "endpoint": "/accounts",
        "response_key": "accounts",
        "table": "account",
        "cursor_key": "accounts_cursor",
        "last_updated_key": "accounts_last_updated_at",
        "supports_pagination": False,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/subsidiaries",
        "response_key": "subsidiaries",
        "table": "subsidiary",
        "cursor_key": "subsidiaries_cursor",
        "last_updated_key": "subsidiaries_last_updated_at",
        "supports_pagination": False,
        "supports_updated_gt": False,
    },
    {
        "endpoint": "/products",
        "response_key": "products",
        "table": "product",
        "cursor_key": "products_cursor",
        "last_updated_key": "products_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": False,
    },
    {
        "endpoint": "/customers",
        "response_key": "customers",
        "table": "customer",
        "cursor_key": "customers_cursor",
        "last_updated_key": "customers_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/contracts",
        "response_key": "contracts",
        "table": "contract",
        "cursor_key": "contracts_cursor",
        "last_updated_key": "contracts_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": False,
        "optional": True,
    },
    {
        "endpoint": "/invoices",
        "response_key": "invoices",
        "table": "invoice",
        "cursor_key": "invoices_cursor",
        "last_updated_key": "invoices_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/invoice-payments",
        "response_key": "payments",
        "table": "invoice_payment",
        "cursor_key": "invoice_payments_cursor",
        "last_updated_key": "invoice_payments_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/credit-memos",
        "response_key": "credit_memos",
        "table": "credit_memo",
        "cursor_key": "credit_memos_cursor",
        "last_updated_key": "credit_memos_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/vendors",
        "response_key": "vendors",
        "table": "vendor",
        "cursor_key": "vendors_cursor",
        "last_updated_key": "vendors_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/vendor-credits",
        "response_key": "vendor_credits",
        "table": "vendor_credit",
        "cursor_key": "vendor_credits_cursor",
        "last_updated_key": "vendor_credits_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
        "optional": True,
    },
    {
        "endpoint": "/bills",
        "response_key": "bills",
        "table": "bill",
        "cursor_key": "bills_cursor",
        "last_updated_key": "bills_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/charges",
        "response_key": "charges",
        "table": "charge",
        "cursor_key": "charges_cursor",
        "last_updated_key": "charges_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/reimbursements",
        "response_key": "reimbursements",
        "table": "reimbursement",
        "cursor_key": "reimbursements_cursor",
        "last_updated_key": "reimbursements_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/journal-entries",
        "response_key": "journal_entries",
        "table": "journal_entry",
        "cursor_key": "journal_entries_cursor",
        "last_updated_key": "journal_entries_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/bank-accounts",
        "response_key": "accounts",
        "table": "bank_account",
        "cursor_key": "bank_accounts_cursor",
        "last_updated_key": "bank_accounts_last_updated_at",
        "supports_pagination": False,
        "supports_updated_gt": False,
    },
    {
        "endpoint": "/bank-transactions",
        "response_key": "bank_transactions",
        "table": "bank_transaction",
        "cursor_key": "bank_transactions_cursor",
        "last_updated_key": "bank_transactions_last_updated_at",
        "supports_pagination": True,
        "supports_updated_gt": True,
    },
    {
        "endpoint": "/tax-rates",
        "response_key": "tax_rates",
        "table": "tax_rate",
        "cursor_key": "tax_rates_cursor",
        "last_updated_key": "tax_rates_last_updated_at",
        "supports_pagination": False,
        "supports_updated_gt": False,
    },
    {
        "endpoint": "/fields",
        "response_key": "fields",
        "table": "field",
        "cursor_key": "fields_cursor",
        "last_updated_key": "fields_last_updated_at",
        "supports_pagination": False,
        "supports_updated_gt": True,
    },
]
