# This is a simple example for how to use FileUpload with the fivetran_connector_sdk
# module to upload unstructured files (PDFs, images, etc.) alongside metadata rows.
# It demonstrates the complete file lifecycle: upload, update, and delete operations.
# See the Technical Reference documentation (https://fivetran.com/docs/connectors/connector-sdk/technical-reference)
# and the Best Practices documentation (https://fivetran.com/docs/connectors/connector-sdk/best-practices) for details.

# Import required classes from fivetran_connector_sdk
# For supporting Connector operations like Update() and Schema()
from fivetran_connector_sdk import Connector

# For enabling Logs in your connector code
from fivetran_connector_sdk import Logging as log

# For supporting Data operations like Upsert(), Update(), Delete() and checkpoint()
from fivetran_connector_sdk import Operations as op

# For uploading files alongside metadata rows
from fivetran_connector_sdk import FileUpload

# For working with in-memory file streams
import io

# For timestamp generation
from datetime import datetime, timezone

# For making HTTP requests to fetch files from public URLs
import requests


def schema(configuration: dict) -> list:
    """
    Define schema for file tracking.

    When you upload files using FileUpload, Fivetran automatically adds a
    _fivetran_file_path column that stores the path from FileUpload.path.

    You DON'T need to define _fivetran_file_path in columns - it's automatic!

    Returns:
        List with one table schema
    """
    return [
        {
            "table": "documents",
            "primary_key": ["doc_id"],
            "columns": {
                "doc_id": "STRING",
                "doc_name": "STRING",
                "doc_version": "STRING",
            },
        }
    ]


def update(configuration: dict, state: dict):
    """
    Demonstrate file upload, update, and delete lifecycle.

    This shows:
    - How to upload a new file
    - How to update an existing file (same primary key, new file)
    - How to delete a file
    - How _fivetran_file_path changes through the lifecycle
    - Basic state management with checkpoint

    Args:
        configuration: Connector configuration
        state: Previous sync state (empty for first run)
    """

    log.info("=" * 80)
    log.info("BASIC UPLOAD EXAMPLE: File Lifecycle Demonstration")
    log.info("=" * 80)

    # ==========================================================================
    # PHASE 1: UPLOAD (Create new file)
    # ==========================================================================
    log.info("\n PHASE 1: UPLOAD - Creating new file")
    log.info("-" * 80)

    try:
        # Fetch a simple PDF from a public URL
        pdf_url = (
            "https://raw.githubusercontent.com/mozilla/pdf.js/master/test/pdfs/tracemonkey.pdf"
        )

        log.info(f"Fetching file from: {pdf_url}")
        response = requests.get(pdf_url, stream=True, timeout=30)
        response.raise_for_status()
        response.raw.decode_content = True

        file_size = int(response.headers.get("content-length", 0))
        log.info(f"File size: {file_size} bytes")

        # Upload the file with metadata using op.upsert()
        # After this operation, this will be the state in the destination:
        # | doc_id     | doc_name           | doc_version | _fivetran_file_path          |
        # |------------|--------------------|-------------|------------------------------|
        # | demo_doc_1 | tracemonkey_v1.pdf | v1          | documents/v1/tracemonkey.pdf |
        #
        # The _fivetran_file_path column is auto-generated by Fivetran
        op.upsert(
            table="documents",
            data={
                "doc_id": "demo_doc_1",
                "doc_name": "tracemonkey_v1.pdf",
                "doc_version": "v1",
            },
            file=FileUpload(path="documents/v1/tracemonkey.pdf", stream=response.raw),
        )

        log.info("File uploaded successfully")

    except Exception as e:
        log.error(f"Upload failed: {e}")
        raise

    # ==========================================================================
    # PHASE 2: UPDATE (Replace existing file)
    # ==========================================================================
    log.info("\n PHASE 2: UPDATE - Replacing existing file")
    log.info("-" * 80)

    try:
        # Fetch a different file (simulating an update)
        csv_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

        log.info(f"Fetching new file from: {csv_url}")
        response = requests.get(csv_url, timeout=30)
        response.raise_for_status()

        file_content = response.content
        file_size = len(file_content)
        log.info(f"New file size: {file_size} bytes")

        # ======================================================================
        # Approach 1: Using op.upsert() - Replaces ALL columns
        # ======================================================================
        log.info("\nApproach 1: Using op.upsert() - must provide ALL columns")

        # upsert() requires ALL column values (unprovided columns become NULL)
        # After this operation, this will be the state in the destination:
        # | doc_id     | doc_name           | doc_version | _fivetran_file_path          |
        # |------------|--------------------| ------------|------------------------------|
        # | demo_doc_1 | tracemonkey_v2.csv | v2          | documents/v2/tracemonkey.csv |
        #
        # Notice: Same doc_id, but new file_name and _fivetran_file_path
        # The old documents/v1/tracemonkey.pdf is replaced
        op.upsert(
            table="documents",
            data={
                "doc_id": "demo_doc_1",  # Same primary key as before - this triggers the update
                "doc_name": "tracemonkey_v2.csv",
                "doc_version": "v2",  # ALL columns must be provided
            },
            file=FileUpload(path="documents/v2/tracemonkey.csv", stream=io.BytesIO(file_content)),
        )

        log.info("File updated with upsert() - all columns replaced")

        # ======================================================================
        # Approach 2: Using op.update() - Updates only specified columns
        # ======================================================================
        log.info("\nApproach 2: Using op.update() - only provide columns to change (RECOMMENDED)")

        # Fetch another file for the second update
        json_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
        response2 = requests.get(json_url, timeout=30)
        response2.raise_for_status()
        file_content2 = response2.content

        # update() only requires primary key + columns you want to change
        # Other columns (like doc_name from v2) remain unchanged
        # After this operation, this will be the state in the destination:
        # | doc_id     | doc_name (unchanged)  | doc_version | _fivetran_file_path          |
        # |------------|---------------------- | ------------|------------------------------|
        # | demo_doc_1 | tracemonkey_v2.csv    | v3          | documents/v3/tracemonkey.csv |
        #
        # Notice: Only doc_version and file path changed, doc_name remains from v2
        # The old documents/v2/tracemonkey.csv is replaced
        op.update(
            table="documents",
            modified={
                "doc_id": "demo_doc_1",  # Primary key (required)
                "doc_name": "tracemonkey_v3.csv",  # Only columns you want to change
                # doc_version is NOT provided, so it keeps the value from v2
            },
            file=FileUpload(path="documents/v3/tracemonkey.csv", stream=io.BytesIO(file_content2)),
        )

        log.info("File updated with update() - only specified columns changed")

        log.info("\n Both update approaches demonstrated successfully")

    except Exception as e:
        log.error(f"Update failed: {e}")
        raise

    # ==========================================================================
    # PHASE 3: DELETE (Soft-delete)
    # ==========================================================================
    log.info("\n️  PHASE 3: DELETE - Soft-delete behavior")
    log.info("-" * 80)

    try:
        # Soft-delete marks the row with _fivetran_deleted = True
        # After this operation, this will be the state in the destination:
        # | doc_id     | doc_name           | doc_version | _fivetran_deleted | _fivetran_file_path          |
        # |------------|--------------------| ------------|-------------------|------------------------------|
        # | demo_doc_1 | tracemonkey_v2.csv | v3          | True              | documents/v3/tracemonkey.csv |
        #
        # Notice: Row is still present with _fivetran_deleted = True
        # The file ALSO remains in the destination stage
        #
        # To query only active (non-deleted) rows:
        # SELECT * FROM documents WHERE _fivetran_deleted IS NULL OR _fivetran_deleted = False;
        op.delete(table="documents", keys={"doc_id": "demo_doc_1"})

        log.info("Row soft-deleted successfully (_fivetran_deleted = True)")
        log.info("Note: Both row and file remain in the destination")

    except Exception as e:
        log.error(f"Delete failed: {e}")
        raise

    # NOTE: The old file is automatically deleted only when you update the row with a
    # DIFFERENT file path (see PHASE 2: UPDATE above). There is no way to delete only
    # the file while keeping the metadata row.

    # ==========================================================================
    # STATE MANAGEMENT
    # ==========================================================================
    log.info("\n💾 STATE MANAGEMENT")
    log.info("-" * 80)

    # Update state for incremental syncs
    state["last_updated"] = datetime.now(timezone.utc).isoformat()

    # Checkpoint saves the state for the next sync
    op.checkpoint(state)

    log.info("Checkpoint saved")

    # ==========================================================================
    # SUMMARY
    # ==========================================================================
    log.info("\n" + "=" * 80)
    log.info("LIFECYCLE SUMMARY")
    log.info("=" * 80)
    log.info("")
    log.info("Operation Flow:")
    log.info(
        "  1. Upload      → doc_id: 'demo_doc_1', file: v1.pdf, path: documents/v1/tracemonkey.pdf"
    )
    log.info(
        "  2. Update (upsert) → doc_id: 'demo_doc_1', file: v2.csv, path: documents/v2/tracemonkey.csv (all columns)"
    )
    log.info(
        "  3. Update (update) → doc_id: 'demo_doc_1', file: v3.csv, path: documents/v3/tracemonkey.csv (partial columns)"
    )
    log.info(
        "  4. Delete      → Row marked with _fivetran_deleted=True, row AND file remain in destination"
    )
    log.info("")
    log.info("Key Takeaways:")
    log.info("  ✓ _fivetran_file_path is auto-generated (you don't create it)")
    log.info("  ✓ upsert() requires ALL columns, update() only columns you want to change")
    log.info("  ✓ op.delete() soft-deletes (_fivetran_deleted=True), row and file remain")
    log.info("  ✓ Old file deleted automatically when updating with different path")
    log.info("  ✓ Checkpoint saves state for incremental syncs")
    log.info("=" * 80)


# Create the connector instance
connector = Connector(update=update, schema=schema)


if __name__ == "__main__":
    # Test locally with: fivetran debug
    connector.debug()
