# This is a simple example for how to use FileUpload with the fivetran_connector_sdk
# module to upload unstructured files (PDFs, images, etc.) alongside metadata rows.
# It demonstrates the complete file lifecycle: upload, update, and delete operations.
# See the Technical Reference documentation (https://fivetran.com/docs/connectors/connector-sdk/technical-reference)
# and the Best Practices documentation (https://fivetran.com/docs/connectors/connector-sdk/best-practices) for details.

# Import required classes from fivetran_connector_sdk
# For supporting Connector operations like Update() and Schema()
from fivetran_connector_sdk import Connector

# For enabling Logs in your connector code
from fivetran_connector_sdk import Logging as log

# For supporting Data operations like Upsert(), Update(), Delete() and checkpoint()
from fivetran_connector_sdk import Operations as op

# For uploading files alongside metadata rows
from fivetran_connector_sdk import FileUpload

# For working with in-memory file streams
import io

# For timestamp generation
from datetime import datetime, timezone

# For making HTTP requests to fetch files from public URLs
import requests


def schema(configuration: dict) -> list:
    """
    Define schema for file tracking.
    
    Fivetran automatically adds a _fivetran_file_path column to store 
    the cloud storage location of uploaded files when you use FileUpload.
    
    You DON'T need to define _fivetran_file_path in columns - it's automatic!
    
    Returns:
        List with one table schema
    """
    return [
        {
            "table": "documents",
            "primary_key": ["doc_id"],
            "columns": {
                "doc_id": "STRING",
                "doc_name": "STRING",
                "doc_version": "STRING",
                "operation_type": "STRING",  # "upload", "update", or "delete"
                "synced_at": "STRING",
                # NOTE: _fivetran_file_path is automatically added by Fivetran
            },
        }
    ]


def update(configuration: dict, state: dict):
    """
    Demonstrate file upload, update, and delete lifecycle.
    
    This shows:
    - How to upload a new file
    - How to update an existing file (same primary key, new file)
    - How to delete a file
    - How _fivetran_file_path changes through the lifecycle
    - Basic state management with checkpoint
    
    Args:
        configuration: Connector configuration
        state: Previous sync state (empty for first run)
    """
    
    log.info("=" * 80)
    log.info("BASIC UPLOAD EXAMPLE: File Lifecycle Demonstration")
    log.info("=" * 80)
    
    # ==========================================================================
    # PHASE 1: UPLOAD (Create new file)
    # ==========================================================================
    log.info("\n📤 PHASE 1: UPLOAD - Creating new file")
    log.info("-" * 80)
    
    try:
        # Fetch a simple PDF from a public URL
        pdf_url = "https://raw.githubusercontent.com/mozilla/pdf.js/master/test/pdfs/tracemonkey.pdf"
        
        log.info(f"Fetching file from: {pdf_url}")
        response = requests.get(pdf_url, stream=True, timeout=30)
        response.raise_for_status()
        response.raw.decode_content = True
        
        file_size = int(response.headers.get("content-length", 0))
        log.info(f"File size: {file_size} bytes")
        
        # Upload the file with metadata using op.upsert()
        # After sync completes, the destination will show:
        # | doc_id     | doc_name           | _fivetran_file_path              |
        # |------------|--------------------|----------------------------------|
        # | demo_doc_1 | tracemonkey_v1.pdf | s3://fivetran-files/.../v1.pdf   |
        #
        # The _fivetran_file_path column is auto-generated by Fivetran
        op.upsert(
            table="documents",
            data={
                "doc_id": "demo_doc_1",
                "doc_name": "tracemonkey_v1.pdf",
                "doc_version": "v1",
                "operation_type": "upload",
                "synced_at": datetime.now(timezone.utc).isoformat(),
            },
            file=FileUpload(path="tracemonkey_v1.pdf", stream=response.raw)
        )
        
        log.info("File uploaded successfully")
        
    except Exception as e:
        log.error(f"Upload failed: {e}")
        raise
    
    # ==========================================================================
    # PHASE 2: UPDATE (Replace existing file)
    # ==========================================================================
    log.info("\n🔄 PHASE 2: UPDATE - Replacing existing file")
    log.info("-" * 80)
    
    try:
        # Fetch a different file (simulating an update)
        csv_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
        
        log.info(f"Fetching new file from: {csv_url}")
        response = requests.get(csv_url, timeout=30)
        response.raise_for_status()
        
        file_content = response.content
        file_size = len(file_content)
        log.info(f"New file size: {file_size} bytes")
        
        # Update the same doc_id with a new file using op.upsert() (insert-or-update)
        # You can also use op.update() instead (update existing row only)
        # Both can accept full or partial column data
        #
        # After sync, the destination will show:
        # | doc_id     | doc_name           | doc_version | _fivetran_file_path              |
        # |------------|--------------------| ------------|----------------------------------|
        # | demo_doc_1 | tracemonkey_v2.csv | v2          | s3://fivetran-files/.../v2.csv   |
        #
        # Notice: Same doc_id, but new file_name and _fivetran_file_path
        # The old v1.pdf is replaced and will be garbage collected
        op.upsert(
            table="documents",
            data={
                "doc_id": "demo_doc_1",  # Same primary key as before - this triggers the update
                "doc_name": "tracemonkey_v2.csv",
                "doc_version": "v2",
                "operation_type": "update",
                "synced_at": datetime.now(timezone.utc).isoformat(),
            },
            file=FileUpload(path="tracemonkey_v2.csv", stream=io.BytesIO(file_content))
        )
        
        # Alternative: Using op.update() (update existing row)
        # op.update(
        #     table="documents",
        #     data={
        #         "doc_id": "demo_doc_1",
        #         "doc_name": "tracemonkey_v2.csv",
        #         "doc_version": "v2",
        #     },
        #     file=FileUpload(path="tracemonkey_v2.csv", stream=io.BytesIO(file_content))
        # )
        
        log.info("File updated successfully")
        
    except Exception as e:
        log.error(f"Update failed: {e}")
        raise
    
    # ==========================================================================
    # PHASE 3: DELETE OPTIONS
    # ==========================================================================
    log.info("\n🗑️  PHASE 3: DELETE OPTIONS - Two different deletion behaviors")
    log.info("-" * 80)
    
    # Option A: Soft-delete the metadata row (file remains in destination stage)
    log.info("\nOption A: Soft-delete metadata row (file stays in destination)")
    log.info("-" * 80)
    
    try:
        # This marks the row as deleted but does NOT delete the staged file
        # After sync completes:
        # SELECT * FROM documents WHERE doc_id = 'demo_doc_1';
        # Result: Empty (0 rows) - but file still exists in destination stage!
        #
        # Use this when you want to remove the row but keep the file
        op.delete(
            table="documents",
            data={"doc_id": "demo_doc_1"}
        )
        
        log.info("Row soft-deleted successfully")
        
    except Exception as e:
        log.error(f"Delete failed: {e}")
        raise
    
    # NOTE: There is no direct way to delete only the file while keeping the metadata row.
    # The old file is automatically deleted only when you update the row with a DIFFERENT
    # file path (see PHASE 2: UPDATE above).
    
    # ==========================================================================
    # STATE MANAGEMENT
    # ==========================================================================
    log.info("\n💾 STATE MANAGEMENT")
    log.info("-" * 80)
    
    # Update state to track what we've done
    # This allows incremental syncs where you:
    #   - Read last_sync timestamp from state
    #   - Fetch only new/modified files since last_sync
    #   - Update state with new timestamp
    #   - Checkpoint to save for next sync
    state["last_sync"] = datetime.now(timezone.utc).isoformat()
    state["operations_completed"] = ["upload", "update", "delete"]
    
    # Checkpoint saves the state for the next sync
    op.checkpoint(state)
    
    log.info("Checkpoint saved")
    
    # ==========================================================================
    # SUMMARY
    # ==========================================================================
    log.info("\n" + "=" * 80)
    log.info("LIFECYCLE SUMMARY")
    log.info("=" * 80)
    log.info("")
    log.info("Operation Flow:")
    log.info("  1. Upload    → doc_id: 'demo_doc_1', file: v1.pdf, path: s3://.../v1.pdf")
    log.info("  2. Update    → doc_id: 'demo_doc_1', file: v2.csv, path: s3://.../v2.csv")
    log.info("  3. Delete    → Row soft-deleted, file remains in destination stage")
    log.info("")
    log.info("Key Takeaways:")
    log.info("  ✓ _fivetran_file_path is auto-generated (you don't create it)")
    log.info("  ✓ Update = upsert with same primary key + new FileUpload")
    log.info("  ✓ Delete row = op.delete() (file stays in destination)")
    log.info("  ✓ Old file deleted automatically when updating with different path")
    log.info("  ✓ Checkpoint saves state for incremental syncs")
    log.info("=" * 80)
    
    return state


# Create the connector instance
connector = Connector(update=update, schema=schema)


if __name__ == "__main__":
    # Test locally with: fivetran debug
    connector.debug()
