name: Check Python Formatting

on:
  pull_request:
    paths:
      - '**.py'
  push:
    branches: [main]

jobs:
  check-python-formatting:
    name: Python Formatting Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install black

      - name: Run black and generate diff
        id: black_check
        run: |
          echo "Running black in check mode with diff output..."
          black --check --diff --line-length 99 . > formatting.diff || true

          if [ -s formatting.diff ]; then
            echo "Formatting issues detected:"
            cat formatting.diff
            echo "black_failed=true" >> $GITHUB_OUTPUT
          else
            echo "No formatting issues found."
          fi

      - name: Upload formatting.diff
        if: steps.black_check.outputs.black_failed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: python-formatting-diff
          path: formatting.diff

      - name: Fail if formatting issues were found
        if: steps.black_check.outputs.black_failed == 'true'
        run: |
          echo "Python formatting check failed. See formatting.diff for details."
          echo "To fix the error(s) run the command below from the root of the repo and commit the changes:"
          echo "./scripts/fix-python-formatting.sh"
          exit 1
