name: PR size label
on:
  pull_request:

jobs:
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label PR by size
        uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            { "0":"XS", "20":"S", "50":"M", "100":"L", "500":"XL", "1000":"XXL" }
